apiVersion: apps/v1
kind: Deployment
metadata:
  name: g73-order-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g73-order-api
  template:
    metadata:
      labels:
        app: g73-order-api
    spec:
      containers:
        - name: g73-order-api
          image: igorramos/g73-order-api:v1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: dev
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_SSLMODE
              value: '?sslmode=disable'
            - name: MIGRATIONS_PATH
              value: "../migrations"
            - name: DEFAULT_TIMEOUT
              value: 10s
            - name: PORT
              value: '8080'
                
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"