// Code generated by MockGen. DO NOT EDIT.
// Source: rowswrapper.go
//
// Generated by this command:
//
//	mockgen -source=rowswrapper.go -destination=mocks/rowswrapper.go
//

// Package mock_sql is a generated GoMock package.
package mock_sql

import (
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRowsWrapper is a mock of RowsWrapper interface.
type MockRowsWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockRowsWrapperMockRecorder
}

// MockRowsWrapperMockRecorder is the mock recorder for MockRowsWrapper.
type MockRowsWrapperMockRecorder struct {
	mock *MockRowsWrapper
}

// NewMockRowsWrapper creates a new mock instance.
func NewMockRowsWrapper(ctrl *gomock.Controller) *MockRowsWrapper {
	mock := &MockRowsWrapper{ctrl: ctrl}
	mock.recorder = &MockRowsWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowsWrapper) EXPECT() *MockRowsWrapperMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRowsWrapper) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRowsWrapperMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRowsWrapper)(nil).Close))
}

// ColumnTypes mocks base method.
func (m *MockRowsWrapper) ColumnTypes() ([]*sql.ColumnType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ColumnTypes")
	ret0, _ := ret[0].([]*sql.ColumnType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ColumnTypes indicates an expected call of ColumnTypes.
func (mr *MockRowsWrapperMockRecorder) ColumnTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ColumnTypes", reflect.TypeOf((*MockRowsWrapper)(nil).ColumnTypes))
}

// Columns mocks base method.
func (m *MockRowsWrapper) Columns() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Columns")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Columns indicates an expected call of Columns.
func (mr *MockRowsWrapperMockRecorder) Columns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Columns", reflect.TypeOf((*MockRowsWrapper)(nil).Columns))
}

// Err mocks base method.
func (m *MockRowsWrapper) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockRowsWrapperMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockRowsWrapper)(nil).Err))
}

// Next mocks base method.
func (m *MockRowsWrapper) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockRowsWrapperMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRowsWrapper)(nil).Next))
}

// NextResultSet mocks base method.
func (m *MockRowsWrapper) NextResultSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextResultSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NextResultSet indicates an expected call of NextResultSet.
func (mr *MockRowsWrapperMockRecorder) NextResultSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextResultSet", reflect.TypeOf((*MockRowsWrapper)(nil).NextResultSet))
}

// Scan mocks base method.
func (m *MockRowsWrapper) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRowsWrapperMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRowsWrapper)(nil).Scan), dest...)
}
