// Code generated by MockGen. DO NOT EDIT.
// Source: order_notify.go
//
// Generated by this command:
//
//	mockgen -source=order_notify.go -destination=mocks/order_notify.go
//
// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	reflect "reflect"

	events "github.com/IgorRamosBR/g73-techchallenge-order/pkg/events"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderNotify is a mock of OrderNotify interface.
type MockOrderNotify struct {
	ctrl     *gomock.Controller
	recorder *MockOrderNotifyMockRecorder
}

// MockOrderNotifyMockRecorder is the mock recorder for MockOrderNotify.
type MockOrderNotifyMockRecorder struct {
	mock *MockOrderNotify
}

// NewMockOrderNotify creates a new mock instance.
func NewMockOrderNotify(ctrl *gomock.Controller) *MockOrderNotify {
	mock := &MockOrderNotify{ctrl: ctrl}
	mock.recorder = &MockOrderNotifyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderNotify) EXPECT() *MockOrderNotifyMockRecorder {
	return m.recorder
}

// NotifyPaymentOrder mocks base method.
func (m *MockOrderNotify) NotifyPaymentOrder(order events.OrderProductionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPaymentOrder", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPaymentOrder indicates an expected call of NotifyPaymentOrder.
func (mr *MockOrderNotifyMockRecorder) NotifyPaymentOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPaymentOrder", reflect.TypeOf((*MockOrderNotify)(nil).NotifyPaymentOrder), order)
}
